### ISSUE TITLE
SafeConfigParser was Removed in Python 3.12

### ISSUE THREAD

**Issue by doncato** [infertux/zeyple#76]
The zeyple script currently does not work in python 3.12 (which is for example the shipped python Version in Ubuntu 24.04)

For me I only seem to encountered the following issue: `ImportError: cannot import name 'SafeConfigParser' from 'configparser'`

The docs state, that since Python version 3.12:
> [configparser](https://docs.python.org/3.12/library/configparser.html#module-configparser) no longer has a SafeConfigParser class. Use the shorter [ConfigParser](https://docs.python.org/3.12/library/configparser.html#configparser.ConfigParser) name instead.

(Source: https://docs.python.org/3.12/whatsnew/3.12.html#configparser)

A possible solution / workaround could be to change [Line 17 in zeyple.py](https://github.com/infertux/zeyple/blob/cc125b7b44432542b227887fd7e2701f77fd8ca2/zeyple/zeyple.py#L17C5-L17C58) to be something like:

```py
from configparser import ConfigParser as SafeConfigParser  # Python 3.12
```
instead. Although this is a bit hacky and will make it incompatible to older python3 versions, so maybe another `try` block would make more sense
